source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'OCLibraryExample' do

end

target 'OCLibraryExampleTests' do

end

target 'OCAppleTVExample' do
platform :tvos, '9.0'
pod 'Alamofire', '~> 3.0'
pod 'SWXMLHash', '~> 2.0.0'
end
